CREATE TABLE shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_number VARCHAR(100) NOT NULL CONSTRAINT sp_tracking_number UNIQUE,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    status VARCHAR(100) NOT NULL,
    weight_kg numeric(10,2) NOT NULL,
    price numeric(12,2) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE shipment_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT NOT NULL REFERENCES shipments(id),
    status VARCHAR(100) NOT NULL,
    note VARCHAR(100),
    occurred_at TIMESTAMP NOT NULL
);